# Generated by Django 4.1.7 on 2023-03-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(default='t6rqKy293EySyJZUDV50ay3TPRzBy0bY', max_length=32),
        ),
    ]
