# Generated by Django 4.1.7 on 2023-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=8, verbose_name='89699139'),
        ),
    ]
