# Generated by Django 4.1.7 on 2023-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailverification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=8, verbose_name='14940172'),
        ),
    ]
